version: '3'

services:
  app:
    build: .
    command: sh -c "yarn typeorm migration:run && yarn dev"
    ports:
      - 3333:3333
    depends_on:
      - dbtest
    # volumes:
    #   - .:/usr/app
  
  dbtest:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret

